### ISSUE TITLE
carrier with specialist doesnt draw specialist after leaving a star

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#389] opened 2020-11-10 21:54 UTC
refreshing browser fixes this

**Comment by mike-eason** [comment] 2020-11-23 20:50
Could not reproduce. Tried the following without refreshing the page:

1. Set waypoints and move.
2. Assign carrier spec, set waypoints and move.
3. Build and assign a spec, set waypoints and move.

Considering this closed unless it can be reproduced.

**Comment by Kurtzmusch** [comment] 2020-11-23 21:37
the problem appears for the other players, not the carrier owner

**Comment by mike-eason** [comment] 2020-11-23 21:51
Great. Managed to reproduce this now, thank you.

**Comment by Kurtzmusch** [comment] 2020-11-23 21:52
actually, this seems to be another firefox exclusive issue... i test things with one accont on firefox and another on chrome so i can quickly submit the turns...

**Comment by Kurtzmusch** [comment] 2020-11-23 21:54
> Great. Managed to reproduce this now, thank you.

really? now i have no idea what is happening then, i thought it was FF

**Comment by mike-eason** [comment] 2020-12-30 21:10
Can no longer reproduce this, closing unless it comes back.

**Closed by mike-eason** 2020-12-30 21:10 UTC
Labels: bug, estimate: 2, good first issue, priority: moderate, status: done
